### ISSUE TITLE
Markdown preview boxes collapse on change

### ISSUE THREAD

**Issue by phazonoverload** [HackCampus/apply#9]
I like increasing the size of a text box before typing a long piece. As soon as I edit a character (add/delete) in a markdown box, it collapsed down.

**Comment by lachenmayer** [comment]
I've struggled with that myself... The problem is that [`bel`](https://www.npmjs.com/package/bel) (which is what [`inu`](npm.im/inu) - the frontend framework we're using - uses under the hood) replaces the real DOM elements, rather than doing diffing on a virtual DOM (as React does).

Seems like a nice idea (simplicity, YAGNI etc), but in hindsight is pretty silly because browser add a lot of additional state to some elements that isn't reflected in the DOM API - like textarea width.

We can solve this by using `contenteditable` divs, but I had some issues with those, can't remember what though. I think placeholders?

fyi the relevant code is here: https://github.com/HackCampus/apply/blob/master/app/client/components/markdownTextArea.js
